apiVersion: v1
kind: Service
metadata:
  name: tugas-ririn-service
spec:
  selector:
    app: tugas-ririn  # mengarah ke pod dengan label app: node-uts
  ports:
    - protocol: TCP
      port: 80        # Port service 
      targetPort: 80 # Port  aplikasi 
  type: LoadBalancer  # Gunakan LoadBalancer untuk akses eksternal, 